mariadb:
    image: mariadb:10.1
    env_file: .env
    ports:
        - "3306:3306"
    restart: always

influx:
    image: tutum/influxdb:0.12
    env_file: .env
    ports:
        - "8086:8086"
    volumes:
        - /var/influxdb:/data
    restart: always

grafana:
    image: grafana/grafana:latest
    env_file: .env
    ports:
        - "3000:3000"
    links:
        - influx
    restart: always
